import type { ContentRepository } from "@/lib/repositories/content-repository";
import {
  addCategory,
  addCourseRecord,
  addLessonRecord,
  addMediaAsset,
  addVideo,
  deleteCategory,
  deleteCourseRecord,
  deleteLessonRecord,
  deleteVideo,
  getCourseRecordById,
  getLessonRecordById,
  listCategories,
  listCourseRecords,
  listLessonRecords,
  listLessonRecordsByCourse,
  listMediaAssets,
  listVideos,
  updateCategory,
  updateCourseRecord,
  updateLessonRecord,
  updateVideo,
} from "@/lib/server/data-store";

export const jsonContentRepository: ContentRepository = {
  listCategories,
  addCategory,
  updateCategory,
  deleteCategory,
  listVideos,
  addVideo,
  updateVideo,
  deleteVideo,
  listCourseRecords,
  addCourseRecord,
  getCourseRecordById,
  updateCourseRecord,
  deleteCourseRecord,
  listLessonRecords,
  addLessonRecord,
  listLessonRecordsByCourse,
  getLessonRecordById,
  updateLessonRecord,
  deleteLessonRecord,
  listMediaAssets,
  addMediaAsset,
};
